server:
  port: 30030

spring:
  freemarker:
    suffix: .html
    request-context-attribute: request
  datasource:
    url: jdbc:mysql://${easy-auth.datasource.url}:${easy-auth.datasource.port}/${easy-auth.datasource.database}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: ${easy-auth.datasource.username}
    password: ${easy-auth.datasource.password}
  redis:
    host: ${easy-auth.redis.host}
    port: ${easy-auth.redis.port}
    database: ${easy-auth.redis.database}
  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    top.zhengru.sso: debug

easy-auth:
  sso:
    client:
      #服务端地址
      server-url: ${easy-auth.sso.server-url}
      #客户端注销地址
      logout-url: ${easy-auth.sso.logout-url}
      #客户端密钥信息
      app-id: ${easy-auth.sso.app-id}
      app-secret: ${easy-auth.sso.app-secret}
      #应用默认回调地址
      default-callback-url: ${easy-auth.sso.default-callback-url}