server:
  port: 30030

spring:
  freemarker:
    suffix: .html
    request-context-attribute: request
  redis:
    host: ${easy-auth.redis.host}
    port: ${easy-auth.redis.port}
    database: ${easy-auth.redis.database}
  profiles:
    active: dev

logging:
  level:
    top.zhengru.sso: debug

easy-auth:
  sso:
    client:
      #服务端地址
      server-url: ${easy-auth.sso.server-url}
      #客户端注销地址
      logout-url: ${easy-auth.sso.logout-url}
      #客户端密钥信息
      app-id: ${easy-auth.sso.app-id}
      app-secret: ${easy-auth.sso.app-secret}
      #应用默认回调地址
      default-callback-url: ${easy-auth.sso.default-callback-url}